FROM golang:1.17-alpine AS builder
WORKDIR /apps

COPY . ./

RUN go mod download
RUN go build -o server

# Stage II - copy app binary file
FROM alpine:3.14
WORKDIR /apps

COPY --from=builder /apps/server ./
COPY --from=builder /apps/aws.env ./.env

EXPOSE 8080

CMD ["./server"]